#### Task1
В качестве разрешенных выбраны следующие кодовые комбинации:<br>
  - *Е1=0000110111*
  - *Е2=0000101011*
  - *Е3=1000011001*
  - *Е4=0010010110*

Определить максимальную кратность обнаруживаемых и исправляемых ошибок.<br>
Показать процесс исправления ошибок максимальной кратности при передаче первой
разрешенной кодовой комбинации.

In [8]:
import numpy as np
from random import randrange

def xor(a, b):
    return (a & (~b)) | ((~a) & b)

# messages with length of 10
msg_len = 10;

E1 = 0b0000110111
E2 = 0b0000101011
E3 = 0b1000011001
E4 = 0b0010010110

# example data for t_isp = 2
# E1 = 0b0000000111
# E2 = 0b0010011000
# E3 = 0b0001100000
# E4 = 0b1111111111

# list of messages
msg_list = np.array([0, E1, E2, E3, E4])

msg_list_len = len(msg_list)

# dest array
d = np.array([[0] * msg_list_len] * msg_list_len)

d_list = []

# calc dests
for i in range(1, msg_list_len - 1):
    for j in range(i + 1, msg_list_len):
        d[i][j] = xor(msg_list[i], msg_list[j]).bit_count()
        print(f"d{i}{j} = {d[i][j]}")
        d_list.append(d[i][j])

d_min = min(d_list)
print(f"\nd_min = {d_min}")


# t_ob -- order of error that is able to be detected
print("\nd_min >= t_ob + 1")
t_ob = d_min - 1
print(f"t_ob <= {t_ob}\n")


# t_isp -- order of error that is able to be fixed
print("d_min >= 2*t_isp + 1")
t_isp = (d_min - 1) / 2
print(f"t_isp <= {t_isp}\n")


# any error vector of t_isp order
# error_vec = 0b0 | (1 << randrange(msg_len))
# TODO: if t_isp != 1 add '1' bits in error_vec
error_vec = 0b1000000000
print(f"error_vec = {bin(error_vec)}\n")


# adding error_vec in msg E1
new_E1 = xor(E1, error_vec)
print(f"new_E1 = E1 ^ error_vec = {bin(new_E1)}")


# check dest from new msg to start msgs
min_dest = msg_len + 1
min_dest_i = 0
for i in range(1, msg_list_len):
    dest = xor(msg_list[i], new_E1).bit_count()
    print(f"d{i} = {dest}")

    if dest < min_dest :
        min_dest = dest
        min_dest_i = i

print(f"min_dest = d{min_dest_i} = {min_dest}\n")

if 1 == min_dest_i:
    print(f"Closest msg is E{min_dest_i}")
    print("So it's E1")

d12 = 3
d13 = 5
d14 = 3
d23 = 4
d24 = 6
d34 = 6

d_min = 3

d_min >= t_ob + 1
t_ob <= 2

d_min >= 2*t_isp + 1
t_isp <= 1.0

error_vec = 0b1000000000

new_E1 = E1 ^ error_vec = 0b1000110111
d1 = 1
d2 = 4
d3 = 4
d4 = 4
min_dest = d1 = 1

Closest msg is E1
So it's E1


#### Task 2

Построить линейный код, обеспечивающий исправление одиночных ошибок при передаче
*N=76<sub>10</sub>* сообщений.<br>
Закодировать информацию *И=53<sub>8</sub>* и при действии вектора ошибок
*е1=1000<sub>2</sub>* показать процесс обнаружения и исправления одиночной ошибки.

In [126]:
import math as mt
import numpy as np

msg_num = 46
e1 = np.array([1, 0, 0])
oct_info = 0o45
info = [int(i) for i in list('{0:0b}'.format(oct_info))]

# order of error that is able to be fixed
t_isp = 1

# printing given info
print(f"msg_num = {msg_num}")
print(f"e1 = {e1}")
print(f"info = {oct(oct_info)}")
print(f"t_isp = {t_isp}")

info_length = mt.ceil(mt.log2(msg_num))
print(f"\ninfo_length = {info_length}")

crc_length = 0

# sum_length = crc_length + info_length
# 2^crc_l >= info_l + crc_l + 1
while pow(2, crc_length) < info_length + crc_length + 1 :
    crc_length+=1

print("\n2^crc_l >= crc_l + info_l + 1")
print(f"crc_lentgh = {crc_length}")

# d_min >= 2 * t_isp + 1
d_min = 2 * t_isp + 1

print(f"\nd_min >= 2 * t + 1 = {d_min}\n")

# number of '1' in crc row is >= d_min - 1
# TODO: if info length is not 6 add/remove row
crc_mtrx = np.matrix([[0, 0, 1, 1],
                        [0, 1, 1, 0],
                        [1, 1, 0, 0],
                        [1, 0, 0, 1],
                        [1, 1, 0, 1],
                        [1, 1, 1, 1]])

# concatinate identity mtrx size of info length and crc_mtrx
full_mtrx = np.concatenate((np.identity(info_length), crc_mtrx), axis=1)
# full matrix result
print(f"full_mtrx = \n{full_mtrx}\n")

# push front 0 in info while length not eq to info_length
for i in range (len(info), info_length) :
    info.insert(0, 0)
# extended result
print(f"exteneded info = {info}\n")

info_mtrx = np.matrix([info])

E = info_mtrx.dot(full_mtrx) % 2
E = np.squeeze(np.asarray(E))
print(f"E = {E}\n")

# push front 0 in e1 while length not eq to E
for i in range (len(e1), len(E)) :
    e1 = np.insert(e1, 0, 0)

print(f"e1 = {e1}\n")
# convert to matrix type
e1_mtrx = np.matrix(e1)

H = np.concatenate((crc_mtrx, np.identity(crc_length)), axis=0)
print(f"H = \n{H}\n")

# adding error e1 in E
E_new = (e1_mtrx + E) % 2
print(f"E_new = {E_new}")

# got crc part, now check number of row in H eq to S
# this bit contains error
S = E_new.dot(H) % 2
print(f"S = {S}")

for i in range(0, H.shape[0]):
    if (H[i] == S[0]).all() :
        print(f"error_i = {i}")
        err_i = i

E_new[0, err_i] = xor((int)(E_new[0, err_i]), 1)

if (E == E_new).all():
    print("Error fixed!")


msg_num = 46
e1 = [1 0 0]
info = 0o45
t_isp = 1

info_length = 6

2^crc_l >= crc_l + info_l + 1
crc_lentgh = 4

d_min >= 2 * t + 1 = 3

full_mtrx = 
[[1. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]

exteneded info = [1, 0, 0, 1, 0, 1]

E = [1. 0. 0. 1. 0. 1. 0. 1. 0. 1.]

e1 = [0 0 0 0 0 0 0 1 0 0]

H = 
[[0. 0. 1. 1.]
 [0. 1. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

E_new = [[1. 0. 0. 1. 0. 1. 0. 0. 0. 1.]]
S = [[0. 1. 0. 0.]]
error_i = 7
Error fixed!
